### ISSUE TITLE
License (SIL OFL-1.1 ?)

### ISSUE THREAD

**Issue by ghost** [chuahou/badfont#6]
Could you add license info.

I would suggest to use `SIL Open Font License 1.1`

- https://github.com/alexeiva/Arsenal/blob/master/OFL.txt

In FontForge you could apply it to project by open *"Element > Font Info...* <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>F</kbd>*"* dialog and hit button *"Add OFL"* on *"TTF Names"* tab:

![pic.1](https://i.imgur.com/XtIcaOh.png)

**Comment by chuahou** [comment]
I will look into this ASAP. Thank you!

**Comment by chuahou** [comment]
Progress based on [this website](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL#83afb016):

- [x] Add OFL via FontForge
- [x] Add OFL.txt
- [x] Add OFL-FAQ.txt
- [x] Add FONTLOG.txt

**Comment by chuahou** [comment]
This was completed in [v1.1.0](https://github.com/chuahou/badfont/releases/tag/v1.1.0).

Thank you @Symbian9 for your help!
